# Spring Boot configuration
spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
  thymeleaf:
    mode: HTML5
    encoding: UTF-8

  mail:
    host: relay.infotn.it
    port: 25
    username:
    password:

      # Other properties
    properties:
      mail:
        smtp:
          auth: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

          # TLS , port 587
          starttls:
            enable: true

    # SSL, post 465
    #spring.mail.properties.mail.smtp.socketFactory.port = 465
    #spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory




  # Spring JMS Settings
#  jms:
#    listener:
#      auto-startup: true
#      concurrency: 10
#      max-concurrency: 10
#    pub-sub-domain: true
#    template:
#      delivery-mode: persistent
#      priority: 100
#      qos-enabled: true
#      receive-timeout: 1000
#      time-to-live: 36000



  activemq:
    broker-url: tcp://172.26.7.70:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    in-memory: false
    pool:
      enabled: false

  jms:
    pub-sub-domain: false

      #trusted: org.springframework.remoting.support,java.lang,it.tndigit.iot
  #jms:
    #pub-sub-domain: true
    listener:
      concurrency: 1
      max-concurrency: 1


  jpa:
    database: postgresql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      #ddl-auto: none
      #ddl-auto: update
      #ddl-auto: validate
      #ddl-auto: create-drop
      #ddl-auto: create
    properties:
      hibernate:
        default_schema: suiot01
        temp:
          use_jdbc_metadata_defaults: false
        connection:
          connection: utf-8
          CharSet: utf-8
          useUnicode: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true



  main:
    allow-bean-definition-overriding: true

  datasource:
    platform: postgresql
    url: jdbc:postgresql://172.26.7.70:5432/suiot01?characterEncoding=UTF-8
    username: infotn
    password: infotn
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    #initialization-mode: never
    continue-on-error: true
    tomcat:
      connection-properties:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 30000
      remove-abandoned: true
      remove-abandoned-timeout: 55
      max-active: 1000
      test-while-idle: true
    hikari:
      maximum-pool-size: 50

  data:
    neo4j:
      open-in-view: true

  application:
    name: I.O.T.

jwt:
  header: Authorization
  secret: secret-sviluppo-iot



#application:
#  protocollo: http
#  port: 8281

server:
  port: 8281
  tomcat:
    uri-encoding: UTF-8
  origin:
    auth: https://opv-test.tndigit.it/auth
#  ioitalia:
#    tocken-standard: 6141c7757be64538bef931860cb2e5e2




logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.fasterxml.jackson: ERROR
    it.infotn: INFO
    it.infotn.opv.service.command.schedavalutazione: DEBUG
    io.swagger.models: ERROR

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#      base-path: /manage
#  endpoint:
#    health:
#      show-details: always
#    shutdown: 'true'
#


#debug: true
